In [2]:
# Standardize data (0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler
import pandas
import numpy
names = ['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'TEMP','RH','WIND','RAIN','AREA']
dataframe = pandas.read_csv("forestfires.csv", names=names)
array = dataframe.values
# separate array into input and output components
X = array[:,4:12]
Y = array[:,12]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
# summarize transformed data
numpy.set_printoptions(precision=3)
print(rescaledX[0:12,:])


[[-0.806 -1.323 -1.83  -0.861 -1.843  0.412  1.499 -0.073]
 [-0.008 -1.18   0.489 -0.51  -0.153 -0.692 -1.742 -0.073]
 [-0.008 -1.05   0.561 -0.51  -0.739 -0.692 -1.518 -0.073]
 [ 0.191 -1.212 -1.898 -0.005 -1.825  3.234 -0.01   0.603]
 [-0.244 -0.931 -1.799  0.127 -1.291  3.356 -1.239 -0.073]
 [ 0.3   -0.4   -0.242  1.247  0.571 -0.938  0.772 -0.073]
 [ 0.3   -0.343 -0.211 -0.115  0.898 -1.061 -0.513 -0.073]
 [ 0.155  0.54   0.243  0.368 -1.877  2.559 -1.015 -0.073]
 [ 0.064  0.291  0.584 -0.444 -0.998  1.148  0.772 -0.073]
 [ 0.336 -0.357  0.608 -0.422  0.674 -0.263 -0.01  -0.073]
 [ 0.336 -0.357  0.608 -0.422 -0.188  0.412  1.778 -0.073]
 [ 0.391 -0.589  0.666  2.981  0.071 -0.386 -0.01  -0.073]]
